services:
  wireguard:
    build: .
    container_name: amneziawg
    cap_add:
      - NET_ADMIN
      - SYS_MODULE #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SERVERURL=my.server.com #optional
      - SERVERPORT=51820 #optional
      - PEERS=1 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
      - PERSISTENTKEEPALIVE_PEERS= #optional
      - LOG_CONFS=true #optional
      - AWG_Jc=3 #optional
      - AWG_Jmin=40 #optional
      - AWG_Jmax=70 #optional
      - AWG_S1=88 #optional
      - AWG_S2=28 #optional
      - AWG_H1=1211620644 #optional
      - AWG_H2=1243252812 #optional
      - AWG_H3=973157458 #optional
      - AWG_H4=1052671299 #optional
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules #optional
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped